---
# nginx_domain og nginx_certbot_email sættes i group_vars/all/config.yml
nginx_subdomains:
  - cloud
  - auth
  - mail
nginx_proxy_dir: "/opt/nginx-proxy"
# Sæt true under fejlsøgning for at undgå Let's Encrypts rate limits
nginx_certbot_staging: false
