---
# Genbrugte stier fra authentik- og nextcloud-roller
authentik_dir: "/opt/authentik"
authentik_domain: "auth.{{ nginx_domain }}"
nextcloud_domain: "cloud.{{ nginx_domain }}"

# LDAP-forbindelsesparametre
# Host auto-discovers fra Docker bridge-gateway (172.17.0.1 typisk)
nextcloud_ldap_port: 389
nextcloud_ldap_base_dn: "dc={{ nginx_domain.split('.') | join(',dc=') }}"
nextcloud_ldap_bind_dn: "cn=ldapservice,ou=users,dc={{ nginx_domain.split('.') | join(',dc=') }}"
nextcloud_ldap_base_users: "ou=users,dc={{ nginx_domain.split('.') | join(',dc=') }}"
nextcloud_ldap_base_groups: "ou=groups,dc={{ nginx_domain.split('.') | join(',dc=') }}"
