---
authentik_dir: "/opt/authentik"
authentik_url: "https://auth.opgavehelten.dk"
authentik_domain: "auth.opgavehelten.dk"
authentik_ldap_base_dn: "dc=opgavehelten,dc=dk"
authentik_ldap_port: 3389
authentik_outpost_name: "ldap-outpost"
authentik_outpost_container: "ak-outpost-ldap-outpost"
nginx_domain: "opgavehelten.dk"
